spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaudharysadique78/config_repo
          clone-on-start: true
          default-label: main

server:
  port: 8888
